apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bonus-gitlab
spec:
  project: bonus-project
  source:
    repoURL: http://HOST_IP:8080/root/iot-gitlab.git
    targetRevision: master
    path: /
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: gitlab
  syncPolicy:
    automated:
      prune: false
      selfHeal: true