apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: myapp-bonus
  namespace: argocd
spec:
  project: default
  source:
    repoURL: http://{gitlab_ip}/root/bonus.git
    targetRevision: main
    path: .
  destination:
    server: https://kubernetes.default.svc
    namespace: gitlab
  syncPolicy:
    automated:
      prune: true
      selfHeal: true