apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: myapp-gitlab
  namespace: argocd
spec:
  project: default
  source:
    repoURL: http://172.22.0.5/root/iotbonus.git
    targetRevision: main
    path: .
  destination:
    server: https://kubernetes.default.svc
    namespace: gitlab
  syncPolicy:
    automated:
      prune: true
      selfHeal: true