apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gitlab-repo
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'http://your-gitlab-server/root/your-repo.git'
    targetRevision: HEAD
    path: .
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: your-namespace
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
