apiVersion: v1
kind: Secret
metadata:
  name: gitlab-auth
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: git
  url: http://{ip-gitlab}/root/bonus.git
  username: root
  password: 'Taha@123'