apiVersion: v1
kind: Secret
metadata:
  name: gitlab-auth
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: git
  url: http://172.19.0.2/root/bonus.git
  username: root
  password: 12345678