apiVersion: v1
kind: Service
metadata:
  name: myapp-service
  namespace: gitlab
spec:
  selector:
    app: myapp-bonus
  ports:
  - name: gitlab
    port: 80
    targetPort: 8888
    nodePort: 30001
  type: NodePort