apiVersion: v1
kind: Service
metadata:
  name: myapp-service
  namespace: dev
spec:
  selector:
    app: myapp
  ports:
  - name: dev
    port: 80
    targetPort: 8888
    nodePort: 30001
  type: NodePort