Vagrant.configure("2") do |config|
    
    config.vm.define "anassifS" do |server|
        server.vm.box = "bento/ubuntu-16.04" #version
        server.vm.hostname = "anassifS"
        server.vm.network :private_network, ip: "192.168.56.110" #auto_config: false
        server.vm.provider "virtualbox" do |v|
            v.memory = 2048
            v.cpus = 2
            v.name = "anassifS"
        end
        server.vm.provision "shell", path: "script.sh" #type shell , run the script
    end
end