Vagrant.configure("2") do |config|
    config.vm.define "anassifS" do |server|
    server.vm.box = "bento/ubuntu-20.04" #version
    server.vm.hostname = "anassifS"
    server.vm.network :private_network, ip: "192.168.56.110"
    server.vm.provider "virtualbox" do |v|
      v.memory = 1024
      v.cpus = 1
      v.name = "anassifS"
    end
    server.vm.provision "shell", path: "scripts/master.sh" #type shell , run the script
    end

    config.vm.define "anassifSW" do |worker|
      worker.vm.box = "bento/ubuntu-20.04"
      worker.vm.hostname = "anassifSW"
      worker.vm.network :private_network, ip: "192.168.56.111"
      worker.vm.provider "virtualbox" do |v|
        v.memory = 1024
        v.cpus = 1
        v.name = "anassifSW"
      end
      worker.vm.provision "shell", path: "scripts/worker.sh" #type shell , run the script
      end

end