apiVersion: v1
kind: Service
metadata:
  name: myapp-service
  namespace: dev
spec:
  selector:
    app: myapp
    
  ports:
  - name: dev
    nodePort: 30001
    port: 80
    targetPort: 3000
  type: NodePort