Vagrant.configure("2") do |config|
    
    config.vm.define "anassifS" do |server|
        server.vm.box = "bento/ubuntu-20.04" #version
        server.vm.hostname = "anassifS"
        server.vm.network :private_network, ip: "192.168.56.110" #auto_config: false
        # Forward port 80 (HTTP) and port 443 (HTTPS) to access GitLab from the host machine
        config.vm.network "forwarded_port", guest: 80, host: 8080
        config.vm.network "forwarded_port", guest: 443, host: 8443
        server.vm.provider "virtualbox" do |v|
            v.memory = 2048
            v.cpus = 2
            v.name = "anassifS"

        end
        server.vm.provision "shell", path: "scripts/install.sh" #type shell , run the script
    end
end